name: Merge Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main
     - dev

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.operating-system }}
    env:
      working-directory: prototype2021
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest] # windows-2019, macos-10.15]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
      - run: flutter pub get
        working-directory: ${env.working_directory}
      - run: flutter test
        working-directory: ${env.working_directory}
